### ISSUE TITLE
police

### ISSUE THREAD

**Issue by Xens4i** [SpikE-Odets/esx_jewelrobbery#2]
it does not detect if there police online 
my min is on 1 there is 1 police in the city but the store wont be open

**Comment by SpikE-Odets** [comment]
Sorry for the slow response.. but just getting back into FiveM coding.  This script uses a dev resource to verify the jobnumbers for any jobs.   esx.jobnumbers.  I have just rewritten the dev tool, and changed the base code for this script to use the new verision of jobnumbers.  If you use both of these scripts and still have issues with it not seeing the number of police online send me a dm and we can setup a way to figure out what is going on.
